# -*- coding: utf-8 -*-
"""Streamlit Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsQP_LxpUfp4iGWgC23QmwxfFpnSEhzE
"""

pip install streamlit

pip install gdown

pip install streamlit geopandas shapely

import streamlit as st
import pandas as pd
import geopandas as gpd
import gdown
import zipfile
import os

# ID file Google Drive (ubah sesuai dengan ID file Anda)
file_id = '1JhlyvHMU-xi80vaJkAbFJQ40rV9prSap'
url = f'https://drive.google.com/uc?id={file_id}'
output = 'data_shp.zip'

# Ganti 'nama_file_zip_anda.zip' dengan nama file zip Anda yang sebenarnya
file_zip = 'data_shp.zip'

# Check if the zip file exists
if not os.path.exists('data_shp.zip'):
    print("Error: 'data_shp.zip' not found. Make sure you have downloaded the file.")
else:
    # List the contents of the zip file
    with zipfile.ZipFile('data_shp.zip', 'r') as zip_ref:
        print(zip_ref.namelist())

# Mengekstrak file ZIP
with zipfile.ZipFile(file_zip, 'r') as zip_ref:
    zip_ref.extractall('data_shp')

# prompt: solusi apa yang kamu berikan ? jika data shp nya tidak ditemukan

import streamlit as st
import pandas as pd
import geopandas as gpd
import gdown
import zipfile
import os

# ID file Google Drive (ubah sesuai dengan ID file Anda)
file_id = '1JhlyvHMU-xi80vaJkAbFJQ40rV9prSap'
url = f'https://drive.google.com/uc?id={file_id}'
output = 'data_shp.zip'

# Download file jika belum ada
if not os.path.exists(output):
  gdown.download(url, output, quiet=False)

# Ganti 'nama_file_zip_anda.zip' dengan nama file zip Anda yang sebenarnya
file_zip = 'data_shp.zip'

# Check if the zip file exists
if not os.path.exists('data_shp.zip'):
    print("Error: 'data_shp.zip' not found. Make sure you have downloaded the file.")
else:
    # List the contents of the zip file
    with zipfile.ZipFile('data_shp.zip', 'r') as zip_ref:
        print(zip_ref.namelist())

# Mengekstrak file ZIP
with zipfile.ZipFile(file_zip, 'r') as zip_ref:
    zip_ref.extractall('data_shp')